SystemGroup root
User nobody
Group nogroup

AccessLog /tmp/cups/log/access_log
ErrorLog /tmp/cups/log/error_log
PageLog /tmp/cups/log/page_log

CacheDir /tmp/cups/cache
DataDir /usr/share/cups
DocumentRoot /usr/share/doc/cups
RequestRoot /tmp/cups/spool/cups
ServerBin /usr/lib/cups
ServerRoot /etc/storage/cups
StateDir /var/run/cups
TempDir /tmp/cups/spool/cups/tmp

ConfigFilePerm 0640
LogFilePerm 0644
Printcap /tmp/cups/printcap
